### ISSUE TITLE
Joint Training

### ISSUE THREAD

**Issue by Rabona17** [MinkaiXu/GeoLDM#3]
Hi Minkai,

Thanks for the amazing work! I am wondering if in the code the AE and the Diffusion are trained jointly by default (with --train_diffusion and --trainable_ae), instead of training separately?

**Comment by Rabona17** [comment]
And a quick follow up, may I ask where is ES_reg reflected in the code? Thanks!

**Comment by MinkaiXu** [comment]
Hi Yuan,

I left a note here (https://github.com/MinkaiXu/GeoLDM#train-the-geoldm) that:
`
Note: In the paper, we present an encoder early-stopping strategy for training the Autoencoder. However, in later experiments, we found that we can even just keep the encoder untrained and only train the decoder, which is faster and leads to similar results. Our released version uses this strategy. This phenomenon is quite interesting and we are also still actively investigating it.
`

So current implementation is just training the decoder and latent diffusion jointly. But since these two are not connected in the computational graph, they essentially can be viewed as separately trained.

And, similarly, in the implementation, ES_reg is simply reflected as an untrained encoder, an extreme case of ES but with pretty good results (and better efficiency)... I'm also still investigating it.

But yes, if you want, you can still train the AE first by specifying your personalized arguments :)
