### ISSUE TITLE
AutoEncoder

### ISSUE THREAD

**Issue by pearl-rabbit** [MinkaiXu/GeoLDM#4]
Why not use the VAE framework?

**Comment by MinkaiXu** [comment]
We actually want to use VAE at the beginning. We have an ablation study section in the paper's appendix where we discussed our observation: in our experiments, KL regularization doesn't work very well with latent diffusion... 

But I think I still leave the code in the implementation. Maybe it's just because we just didn't find a good hyperparameter set for it, and we are also still investigating it.

**Comment by pearl-rabbit** [comment]
OK~
